apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
        volume.beta.kubernetes.io/storage-class: gp2
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
