apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: superapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: superapp
    spec:
      containers:
      - name: superapp-app-container
        image: myregistry.democompany.com:5000/superapp:1.${BUILD_NUMBER}
        ports:
        - containerPort: 80
