apiVersion: extensions/v1beta1
kind: Service
metadata:
  name: superapp-nodeport
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 32222
    selector:
      app: superapp
