apiVersion: v1
kind: Service
metadata:
  name: superapp-nodeport
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32222
    selector:
      name: superapp
      context: superapp-context
