apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-${TARGET_ROLE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
        role: blue
    spec:
      containers:
      - name: master
        image: technoross/myjenkins:2.149MitraNoVer
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        - name: JAVA_OPTS
          value: '-Xmx1400m -Djenkins.install.runSetupWizard=false'
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-nfs
