apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.100
    path: "/opt/nfs"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 15Gi
