version: "3.4"

services:
  registry:
    image: registry:2.6.2
    hostname: myregistry.democompany.com
    ports:
      - '5000:5000'
    volumes:
      - "/home/centos/localserverdata/registry/data:/var/lib/registry"
      - "/home/centos/localserverdata/registry/certs:/certs"
      - "/home/centos/localserverdata/registry/auth:/auth"
      - "/etc/hosts:/etc/hosts:ro"
    networks:
      - regjen

  jenkins:
    image: 'technoross/sasjenkins:2.122'
    hostname: 'myjenkins.democompany.com'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/centos/localserverdata/jenkins/data:/var/jenkins_home"
      - "/etc/hosts:/etc/hosts:ro"
    networks:
      - regjen

networks:
  regjen:

